AWSTemplateFormatVersion: '2010-09-09'
Description: 'Color Match Rush - Centralized Leaderboard Infrastructure with OAuth'

Parameters:
  TableName:
    Type: String
    Default: 'color-match-rush-scores'
    Description: Name for the DynamoDB table

  AppDomain:
    Type: String
    Default: 'colormatchrush'
    Description: Unique prefix for Cognito hosted UI domain

  CallbackURL:
    Type: String
    Default: 'http://localhost:5173'
    Description: OAuth callback URL (your app URL)

  GoogleClientId:
    Type: String
    Default: ''
    Description: Google OAuth Client ID (leave empty to skip Google setup)

  GoogleClientSecret:
    Type: String
    Default: ''
    NoEcho: true
    Description: Google OAuth Client Secret

  AppleTeamId:
    Type: String
    Default: ''
    Description: Apple Team ID (leave empty to skip Apple setup)

  AppleKeyId:
    Type: String
    Default: ''
    Description: Apple Key ID

  AppleServiceId:
    Type: String
    Default: ''
    Description: Apple Service ID (Client ID)

  ApplePrivateKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: Apple Private Key (contents of .p8 file)

Conditions:
  HasGoogle: !Not [!Equals [!Ref GoogleClientId, '']]
  HasApple: !Not [!Equals [!Ref AppleTeamId, '']]

Resources:
  # DynamoDB Table for storing scores
  ScoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      Tags:
        - Key: Application
          Value: ColorMatchRush

  # Cognito User Pool for authentication
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ColorMatchRushUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false

  # User Pool Domain for hosted UI
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${AppDomain}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  # Google Identity Provider
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasGoogle
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: 'profile email openid'
      AttributeMapping:
        email: email
        name: name
        username: sub

  # Apple Identity Provider
  AppleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasApple
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: SignInWithApple
      ProviderType: SignInWithApple
      ProviderDetails:
        client_id: !Ref AppleServiceId
        team_id: !Ref AppleTeamId
        key_id: !Ref AppleKeyId
        private_key: !Ref ApplePrivateKey
        authorize_scopes: 'email name'
      AttributeMapping:
        email: email
        name: name
        username: sub

  # User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - UserPoolDomain
    Properties:
      ClientName: ColorMatchRushWebClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      SupportedIdentityProviders:
        - COGNITO
        - !If [HasGoogle, Google, !Ref 'AWS::NoValue']
        - !If [HasApple, SignInWithApple, !Ref 'AWS::NoValue']
      CallbackURLs:
        - !Ref CallbackURL
        - !Sub '${CallbackURL}/'
      LogoutURLs:
        - !Ref CallbackURL
        - !Sub '${CallbackURL}/'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

  # Cognito Identity Pool
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: ColorMatchRushIdentityPool
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  # IAM Role for authenticated users
  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref IdentityPool
              ForAnyValue:StringLike:
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: DynamoDBLeaderboardAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:GetItem
                Resource: !GetAtt ScoresTable.Arn

  # IAM Role for unauthenticated users
  UnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref IdentityPool
              ForAnyValue:StringLike:
                'cognito-identity.amazonaws.com:amr': unauthenticated
      Policies:
        - PolicyName: DynamoDBLeaderboardReadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                Resource: !GetAtt ScoresTable.Arn

  # Attach roles to identity pool
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn
        unauthenticated: !GetAtt UnauthenticatedRole.Arn

Outputs:
  Region:
    Description: AWS Region
    Value: !Ref AWS::Region

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref IdentityPool

  CognitoDomain:
    Description: Cognito Hosted UI Domain
    Value: !Sub '${AppDomain}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com'

  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref ScoresTable

  EnvFileContents:
    Description: Copy this to your .env file
    Value: !Sub |
      VITE_AWS_REGION=${AWS::Region}
      VITE_AWS_USER_POOL_ID=${UserPool}
      VITE_AWS_USER_POOL_CLIENT_ID=${UserPoolClient}
      VITE_AWS_IDENTITY_POOL_ID=${IdentityPool}
      VITE_AWS_DYNAMODB_TABLE=${ScoresTable}
      VITE_COGNITO_DOMAIN=${AppDomain}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com
      VITE_REDIRECT_URI=${CallbackURL}
